INSERT INTO Bus (id,name,type,status) VALUES (null,'255','Autobusy','0');
INSERT INTO Bus (id,name,type,status) VALUES (null,'123','Autobusy','0');
INSERT INTO Bus (id,name,type,status) VALUES (null,'166','Autobusy','0');
INSERT INTO Bus (id,name,type,status) VALUES (null,'149','Autobusy','0');
INSERT INTO Bus (id,name,type,status) VALUES (null,'N13','Nocne autobusy','0');
INSERT INTO Bus (id,name,type,status) VALUES (null,'136','Autobusy','1');
INSERT INTO Bus (id,name,type,status) VALUES (null,'151','Autobusy','0');
INSERT INTO Bus (id,name,type,status) VALUES (null,'189','Autobusy','1');
INSERT INTO Bus (id,name,type,status) VALUES (null,'295','Autobusy','0');
INSERT INTO Bus (id,name,type,status) VALUES (null,'269','Autobusy','1');
INSERT INTO Bus (id,name,type,status) VALUES (null,'212','Autobusy','0');
INSERT INTO Bus (id,name,type,status) VALUES (null,'512','Autobusy','0');
INSERT INTO Bus (id,name,type,status) VALUES (null,'108','Autobusy','0');
INSERT INTO Bus (id,name,type,status) VALUES (null,'118','Autobusy','0');
INSERT INTO Bus (id,name,type,status) VALUES (null,'N4','Nocne autobusy','0');
INSERT INTO Bus (id,name,type,status) VALUES (null,'574','Autobusy','0');
INSERT INTO Bus (id,name,type,status) VALUES (null,'256','Autobusy','1');
INSERT INTO Bus (id,name,type,status) VALUES (null,'205','Autobusy','1');
INSERT INTO Bus (id,name,type,status) VALUES (null,'232','Autobusy','1');
INSERT INTO Bus (id,name,type,status) VALUES (null,'7','Tramwaje','0');
INSERT INTO Bus (id,name,type,status) VALUES (null,'N9','Nocne autobusy','0');
INSERT INTO Bus (id,name,type,status) VALUES (null,'169','Autobusy','0');
INSERT INTO Bus (id,name,type,status) VALUES (null,'171','Autobusy','0');
INSERT INTO Bus (id,name,type,status) VALUES (null,'179','Autobusy','0');
INSERT INTO Bus (id,name,type,status) VALUES (null,'112','Autobusy','0');
INSERT INTO Bus (id,name,type,status) VALUES (null,'186','Autobusy','0');
INSERT INTO Bus (id,name,type,status) VALUES (null,'N8','Nocne autobusy','0');
INSERT INTO Bus (id,name,type,status) VALUES (null,'138','Autobusy','0');
INSERT INTO Bus (id,name,type,status) VALUES (null,'606','Autobusy','0');
INSERT INTO Bus (id,name,type,status) VALUES (null,'622','Autobusy','0');
INSERT INTO Bus (id,name,type,status) VALUES (null,'148','Autobusy','1');
INSERT INTO Bus (id,name,type,status) VALUES (null,'178','Autobusy','1');
INSERT INTO Bus (id,name,type,status) VALUES (null,'117','Autobusy','1');
INSERT INTO Bus (id,name,type,status) VALUES (null,'143','Autobusy','1');
INSERT INTO Bus (id,name,type,status) VALUES (null,'N6','Nocne autobusy','1');
INSERT INTO Bus (id,name,type,status) VALUES (null,'N12','Nocne autobusy','1');
INSERT INTO Bus (id,name,type,status) VALUES (null,'131','Autobusy','0');
INSERT INTO Bus (id,name,type,status) VALUES (null,'N11','Nocne autobusy','1');
INSERT INTO Bus (id,name,type,status) VALUES (null,'106','Autobusy','0');
INSERT INTO Bus (id,name,type,status) VALUES (null,'111','Autobusy','0');
INSERT INTO Bus (id,name,type,status) VALUES (null,'200','Autobusy','0');
INSERT INTO Bus (id,name,type,status) VALUES (null,'207','Autobusy','0');
INSERT INTO Bus (id,name,type,status) VALUES (null,'100','Autobusy','1');
INSERT INTO Bus (id,name,type,status) VALUES (null,'155','Autobusy','1');
INSERT INTO Bus (id,name,type,status) VALUES (null,'158','Autobusy','0');
INSERT INTO Bus (id,name,type,status) VALUES (null,'162','Autobusy','1');
INSERT INTO Bus (id,name,type,status) VALUES (null,'188','Autobusy','0');
INSERT INTO Bus (id,name,type,status) VALUES (null,'262','Autobusy','0');
INSERT INTO Bus (id,name,type,status) VALUES (null,'129','Autobusy','1');
INSERT INTO Bus (id,name,type,status) VALUES (null,'2','Tramwaje','1');
INSERT INTO Bus (id,name,type,status) VALUES (null,'3','Tramwaje','1');
INSERT INTO Bus (id,name,type,status) VALUES (null,'4','Tramwaje','1');
INSERT INTO Bus (id,name,type,status) VALUES (null,'5','Tramwaje','0');
INSERT INTO Bus (id,name,type,status) VALUES (null,'6','Tramwaje','0');
INSERT INTO Bus (id,name,type,status) VALUES (null,'8','Tramwaje','0');
INSERT INTO Bus (id,name,type,status) VALUES (null,'9','Tramwaje','0');
INSERT INTO Bus (id,name,type,status) VALUES (null,'10','Tramwaje','0');
INSERT INTO Bus (id,name,type,status) VALUES (null,'11','Tramwaje','0');
INSERT INTO Bus (id,name,type,status) VALUES (null,'12','Tramwaje','0');
INSERT INTO Bus (id,name,type,status) VALUES (null,'N3','Nocne autobusy','0');
INSERT INTO Bus (id,name,type,status) VALUES (null,'110','Autobusy','0');
INSERT INTO Bus (id,name,type,status) VALUES (null,'113','Autobusy','0');
INSERT INTO Bus (id,name,type,status) VALUES (null,'115','Autobusy','0');
INSERT INTO Bus (id,name,type,status) VALUES (null,'116','Autobusy','1');
INSERT INTO Bus (id,name,type,status) VALUES (null,'122','Autobusy','0');
INSERT INTO Bus (id,name,type,status) VALUES (null,'126','Autobusy','1');
INSERT INTO Bus (id,name,type,status) VALUES (null,'130','Autobusy','0');
INSERT INTO Bus (id,name,type,status) VALUES (null,'139','Autobusy','0');
INSERT INTO Bus (id,name,type,status) VALUES (null,'156','Autobusy','0');
INSERT INTO Bus (id,name,type,status) VALUES (null,'157','Autobusy','0');
INSERT INTO Bus (id,name,type,status) VALUES (null,'164','Autobusy','0');
INSERT INTO Bus (id,name,type,status) VALUES (null,'167','Autobusy','0');
INSERT INTO Bus (id,name,type,status) VALUES (null,'168','Autobusy','0');
INSERT INTO Bus (id,name,type,status) VALUES (null,'174','Autobusy','1');
INSERT INTO Bus (id,name,type,status) VALUES (null,'175','Autobusy','1');
INSERT INTO Bus (id,name,type,status) VALUES (null,'184','Autobusy','1');
INSERT INTO Bus (id,name,type,status) VALUES (null,'199','Autobusy','1');
INSERT INTO Bus (id,name,type,status) VALUES (null,'210','Autobusy','1');
INSERT INTO Bus (id,name,type,status) VALUES (null,'213','Autobusy','0');
INSERT INTO Bus (id,name,type,status) VALUES (null,'227','Autobusy','0');
INSERT INTO Bus (id,name,type,status) VALUES (null,'267','Autobusy','1');
INSERT INTO Bus (id,name,type,status) VALUES (null,'283','Autobusy','0');
INSERT INTO Bus (id,name,type,status) VALUES (null,'315','Autobusy','1');
INSERT INTO Bus (id,name,type,status) VALUES (null,'955','Autobusy','0');
INSERT INTO Bus (id,name,type,status) VALUES (null,'F5','Tramwaj wodny','1');
INSERT INTO Bus (id,name,type,status) VALUES (null,'F6','Tramwaj wodny','0');
INSERT INTO Bus (id,name,type,status) VALUES (null,'154','Autobusy','0');
INSERT INTO Bus (id,name,type,status) VALUES (null,'N1','Nocne autobusy','0');
INSERT INTO Bus (id,name,type,status) VALUES (null,'N2','Nocne autobusy','0');
INSERT INTO Bus (id,name,type,status) VALUES (null,'N5','Nocne autobusy','0');
INSERT INTO Bus (id,name,type,status) VALUES (null,'124','Autobusy','1');
INSERT INTO Bus (id,name,type,status) VALUES (null,'127','Autobusy','1');
