ALTER TABLE `busstop` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
INSERT INTO busstop (Id,street) VALUES (null,'Abrahama');
INSERT INTO busstop (Id,street) VALUES (null,'Agrarna');
INSERT INTO busstop (Id,street) VALUES (null,'Agrarna (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Akademia Muzyczna');
INSERT INTO busstop (Id,street) VALUES (null,'Akademia Muzyczna (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Aksamitna');
INSERT INTO busstop (Id,street) VALUES (null,'al. Hallera');
INSERT INTO busstop (Id,street) VALUES (null,'al. Hallera (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'AmberExpo');
INSERT INTO busstop (Id,street) VALUES (null,'AstronautÛw');
INSERT INTO busstop (Id,street) VALUES (null,'AstronautÛw (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Bajana');
INSERT INTO busstop (Id,street) VALUES (null,'Banino');
INSERT INTO busstop (Id,street) VALUES (null,'Banino - Borowiecka');
INSERT INTO busstop (Id,street) VALUES (null,'Banino - Pszenna');
INSERT INTO busstop (Id,street) VALUES (null,'Banino - Szko≥a');
INSERT INTO busstop (Id,street) VALUES (null,'Barniewicka');
INSERT INTO busstop (Id,street) VALUES (null,'Barniewicka (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Baza Manipulacyjna (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'BaøyÒskiego');
INSERT INTO busstop (Id,street) VALUES (null,'BaøyÒskiego (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'BCB Azymutalna');
INSERT INTO busstop (Id,street) VALUES (null,'Belgradzka');
INSERT INTO busstop (Id,street) VALUES (null,'Belgradzka (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Bema');
INSERT INTO busstop (Id,street) VALUES (null,'Bema (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Beniowskiego (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Benzynowa (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Biblioteka G≥Ûwna UG');
INSERT INTO busstop (Id,street) VALUES (null,'Biwakowa');
INSERT INTO busstop (Id,street) VALUES (null,'Biwakowa (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'B≥onia');
INSERT INTO busstop (Id,street) VALUES (null,'B≥onia (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Bobrowa (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Bogatka');
INSERT INTO busstop (Id,street) VALUES (null,'Bogatka (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Bogatka I (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Bogatka II (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Boguckiego (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Bora Komorowskiego');
INSERT INTO busstop (Id,street) VALUES (null,'Bora Komorowskiego (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Brama Oliwska');
INSERT INTO busstop (Id,street) VALUES (null,'Brama Wyøynna');
INSERT INTO busstop (Id,street) VALUES (null,'Brama Øu≥awska');
INSERT INTO busstop (Id,street) VALUES (null,'Brama Øu≥awska (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Bratki');
INSERT INTO busstop (Id,street) VALUES (null,'Bratki (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'BrÍtowo PKM');
INSERT INTO busstop (Id,street) VALUES (null,'BrÍtowo PKM (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Brzeüno');
INSERT INTO busstop (Id,street) VALUES (null,'Brzeüno  (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Buczka');
INSERT INTO busstop (Id,street) VALUES (null,'Buczka (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'BudapesztaÒska');
INSERT INTO busstop (Id,street) VALUES (null,'BudapesztaÒska (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Budowlanych (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Budzysza');
INSERT INTO busstop (Id,street) VALUES (null,'Budzysza Elmont');
INSERT INTO busstop (Id,street) VALUES (null,'Budzysza Elmont (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Bursztynowa (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Bysewo');
INSERT INTO busstop (Id,street) VALUES (null,'Bysewska (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Cebertowicza');
INSERT INTO busstop (Id,street) VALUES (null,'Centrostal (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Centrum Medycyny Inwazyjnej');
INSERT INTO busstop (Id,street) VALUES (null,'Centrum Nadawcze RTV (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Centrum Onkologii (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Cha≥ubiÒskiego');
INSERT INTO busstop (Id,street) VALUES (null,'Cha≥ubiÒskiego (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Charpentiera Wis≥oujúcie (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Che≥m - WiÍckowskiego');
INSERT INTO busstop (Id,street) VALUES (null,'Che≥m Cienista');
INSERT INTO busstop (Id,street) VALUES (null,'Che≥m Cienista (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Che≥m Witosa');
INSERT INTO busstop (Id,street) VALUES (null,'Che≥m Witosa (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Ch≥odna');
INSERT INTO busstop (Id,street) VALUES (null,'Ch≥odna (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Ch≥opska');
INSERT INTO busstop (Id,street) VALUES (null,'Ch≥opska  (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Ch≥opska - ObroÒcÛw Wybrzeøa');
INSERT INTO busstop (Id,street) VALUES (null,'Chmielna');
INSERT INTO busstop (Id,street) VALUES (null,'Chodowieckiego');
INSERT INTO busstop (Id,street) VALUES (null,'Chrzanowskiego');
INSERT INTO busstop (Id,street) VALUES (null,'Chwaszczyno');
INSERT INTO busstop (Id,street) VALUES (null,'Chwaszczyno - GdyÒska (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Chwaszczyno - Oliwska');
INSERT INTO busstop (Id,street) VALUES (null,'Chwaszczyno - Szmaragdowa (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Chwaszczyno - Wiejska');
INSERT INTO busstop (Id,street) VALUES (null,'Ciasna');
INSERT INTO busstop (Id,street) VALUES (null,'CieszyÒskiego');
INSERT INTO busstop (Id,street) VALUES (null,'CieszyÒskiego (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Cio≥kowskiego');
INSERT INTO busstop (Id,street) VALUES (null,'Cio≥kowskiego (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Cmentarna (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Cmentarz £ostowicki');
INSERT INTO busstop (Id,street) VALUES (null,'Cmentarz £ostowicki (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Cmentarz Oliwski');
INSERT INTO busstop (Id,street) VALUES (null,'CygaÒska GÛra');
INSERT INTO busstop (Id,street) VALUES (null,'CygaÒska GÛra (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'CystersÛw');
INSERT INTO busstop (Id,street) VALUES (null,'CystersÛw (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Czarny DwÛr');
INSERT INTO busstop (Id,street) VALUES (null,'Czarny DwÛr (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'CzermiÒskiego');
INSERT INTO busstop (Id,street) VALUES (null,'CzermiÒskiego (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Czerwony DwÛr');
INSERT INTO busstop (Id,street) VALUES (null,'Czerwony DwÛr (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Czyøewskiego (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Damroki');
INSERT INTO busstop (Id,street) VALUES (null,'Damroki (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'DπbrowszczakÛw');
INSERT INTO busstop (Id,street) VALUES (null,'DπbrowszczakÛw - Obr. Wybrz. (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'DπbrowszczakÛw - ObroÒcÛw Wybrzeøa');
INSERT INTO busstop (Id,street) VALUES (null,'De Plelo (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Derdowskiego');
INSERT INTO busstop (Id,street) VALUES (null,'DÍbinki');
INSERT INTO busstop (Id,street) VALUES (null,'D≥ugi Targ');
INSERT INTO busstop (Id,street) VALUES (null,'Dmowskiego');
INSERT INTO busstop (Id,street) VALUES (null,'Dmowskiego (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Dobra (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Dobrowo');
INSERT INTO busstop (Id,street) VALUES (null,'Dobrowo (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Dobrowolskiego');
INSERT INTO busstop (Id,street) VALUES (null,'Dobrowolskiego (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Dolna');
INSERT INTO busstop (Id,street) VALUES (null,'Dolna (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Dolna Brama');
INSERT INTO busstop (Id,street) VALUES (null,'Dolne Miasto');
INSERT INTO busstop (Id,street) VALUES (null,'Dolne M≥yny (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Dom Fahrenheita');
INSERT INTO busstop (Id,street) VALUES (null,'Dragana - K≥adka');
INSERT INTO busstop (Id,street) VALUES (null,'Dragana - Szko≥a');
INSERT INTO busstop (Id,street) VALUES (null,'DroszyÒskiego');
INSERT INTO busstop (Id,street) VALUES (null,'DroszyÒskiego (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'DrwÍcka (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Drzewieckiego');
INSERT INTO busstop (Id,street) VALUES (null,'Drzewieckiego (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Dulkowa (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Dworkowa');
INSERT INTO busstop (Id,street) VALUES (null,'Dworkowa (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Dworska');
INSERT INTO busstop (Id,street) VALUES (null,'Dworska (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Dworzec G≥Ûwny');
INSERT INTO busstop (Id,street) VALUES (null,'Dworzec PKS');
INSERT INTO busstop (Id,street) VALUES (null,'DwÛr FerberÛw (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Dywizjonu 303');
INSERT INTO busstop (Id,street) VALUES (null,'Elblπska - Wiadukt');
INSERT INTO busstop (Id,street) VALUES (null,'Elblπska - Wiadukt (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'ElfÛw');
INSERT INTO busstop (Id,street) VALUES (null,'ElfÛw (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Elmet (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Emaus');
INSERT INTO busstop (Id,street) VALUES (null,'Emaus (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Fabryczna');
INSERT INTO busstop (Id,street) VALUES (null,'Fabryczna (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Falista (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Falowa (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Firoga (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Focha (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Forsycji (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Galeria Ba≥tycka');
INSERT INTO busstop (Id,street) VALUES (null,'Galeria Ba≥tycka (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'GdaÒska');
INSERT INTO busstop (Id,street) VALUES (null,'Gdynia - Anyøowa');
INSERT INTO busstop (Id,street) VALUES (null,'Gdynia - Dπbrowa Centrum');
INSERT INTO busstop (Id,street) VALUES (null,'Gdynia - Gie≥da Towarowa');
INSERT INTO busstop (Id,street) VALUES (null,'Gdynia - Kameliowa');
INSERT INTO busstop (Id,street) VALUES (null,'Gdynia - Karwiny Tesco');
INSERT INTO busstop (Id,street) VALUES (null,'Gdynia - Paprykowa');
INSERT INTO busstop (Id,street) VALUES (null,'Gdynia - Rdestowa - ChwaszczyÒska (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Gdynia - Rdestowa - Leúny Zakπtek (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Gdynia - StarochwaszczyÒska (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Gdynia - Szafranowa');
INSERT INTO busstop (Id,street) VALUES (null,'Gdynia Buraczana (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Gdynia Karwiny Tesco (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Gdynia Myúliwska (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Gdynia Na≥kowskiej (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Gdynia Osiedle Bernadowo (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Gdynia WiczliÒska (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Gdynia èrÛd≥o Marii (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'GÍsia');
INSERT INTO busstop (Id,street) VALUES (null,'GÍsia (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'G≥Íboka');
INSERT INTO busstop (Id,street) VALUES (null,'G≥ucha (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Gospody');
INSERT INTO busstop (Id,street) VALUES (null,'Gospody  (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'GostyÒska (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Goúcinna');
INSERT INTO busstop (Id,street) VALUES (null,'Goúcinna (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'GÛrecka (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'GÛrki Wschodnie');
INSERT INTO busstop (Id,street) VALUES (null,'GÛrki Wschodnie (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'GÛrki Zachodnie');
INSERT INTO busstop (Id,street) VALUES (null,'GÛrskiego');
INSERT INTO busstop (Id,street) VALUES (null,'Grabowskiego');
INSERT INTO busstop (Id,street) VALUES (null,'Gronostajowa');
INSERT INTO busstop (Id,street) VALUES (null,'Grudziπdzka');
INSERT INTO busstop (Id,street) VALUES (null,'Grunwaldzka');
INSERT INTO busstop (Id,street) VALUES (null,'Grunwaldzka (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Hala "Olivia"');
INSERT INTO busstop (Id,street) VALUES (null,'Hallera - Baza ZKM');
INSERT INTO busstop (Id,street) VALUES (null,'Hallera - Baza ZKM (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Helska');
INSERT INTO busstop (Id,street) VALUES (null,'Heweliusza');
INSERT INTO busstop (Id,street) VALUES (null,'Hokejowa');
INSERT INTO busstop (Id,street) VALUES (null,'Hokejowa (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Ikara');
INSERT INTO busstop (Id,street) VALUES (null,'I≥awska');
INSERT INTO busstop (Id,street) VALUES (null,'Instal (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Inøynierska (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Jab≥oniowa (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'JagielloÒska');
INSERT INTO busstop (Id,street) VALUES (null,'JagielloÒska - Przychodnia');
INSERT INTO busstop (Id,street) VALUES (null,'Jana Paw≥a II');
INSERT INTO busstop (Id,street) VALUES (null,'Jana Paw≥a II (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Jankowo');
INSERT INTO busstop (Id,street) VALUES (null,'Jarowa');
INSERT INTO busstop (Id,street) VALUES (null,'Jasia i Ma≥gosi');
INSERT INTO busstop (Id,street) VALUES (null,'JasieÒ - Dzia≥ki');
INSERT INTO busstop (Id,street) VALUES (null,'JasieÒ - Dzia≥ki (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'JasieÒ - PÛlnicy');
INSERT INTO busstop (Id,street) VALUES (null,'JasieÒ PKM');
INSERT INTO busstop (Id,street) VALUES (null,'JasieÒska');
INSERT INTO busstop (Id,street) VALUES (null,'Jaúkowa Dolina');
INSERT INTO busstop (Id,street) VALUES (null,'Jaúkowa Dolina (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'JaworzniakÛw');
INSERT INTO busstop (Id,street) VALUES (null,'Jednoroøca');
INSERT INTO busstop (Id,street) VALUES (null,'JeleniogÛrska');
INSERT INTO busstop (Id,street) VALUES (null,'Jelitkowo');
INSERT INTO busstop (Id,street) VALUES (null,'Jelitkowo Kapliczna');
INSERT INTO busstop (Id,street) VALUES (null,'Jelitkowo Kapliczna (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Jodowa');
INSERT INTO busstop (Id,street) VALUES (null,'Jodowa (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'KaczeÒce');
INSERT INTO busstop (Id,street) VALUES (null,'KaczeÒce - Sienna (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Kamienna Grobla');
INSERT INTO busstop (Id,street) VALUES (null,'Kamienna Grobla (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Kampinoska');
INSERT INTO busstop (Id,street) VALUES (null,'Kampinoska (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Kana≥owa (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Karczemki');
INSERT INTO busstop (Id,street) VALUES (null,'Karczemki (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Karpacka (Cm. Oliwski)');
INSERT INTO busstop (Id,street) VALUES (null,'Karpacka (Cm. Oliwski) (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Karskiego');
INSERT INTO busstop (Id,street) VALUES (null,'Kartuska (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Kasztanowa');
INSERT INTO busstop (Id,street) VALUES (null,'Katarzynki');
INSERT INTO busstop (Id,street) VALUES (null,'Katownia');
INSERT INTO busstop (Id,street) VALUES (null,'Kempingowa');
INSERT INTO busstop (Id,street) VALUES (null,'Kempingowa (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'KÍpna (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Kielecka');
INSERT INTO busstop (Id,street) VALUES (null,'Kielecka (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Kie≥pinek PKM');
INSERT INTO busstop (Id,street) VALUES (null,'Kie≥pino - Szko≥a');
INSERT INTO busstop (Id,street) VALUES (null,'Kie≥pino - Szko≥a (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Kie≥pino GÛrne (Lipuska)');
INSERT INTO busstop (Id,street) VALUES (null,'Kie≥pino GÛrne (WÍsierska)');
INSERT INTO busstop (Id,street) VALUES (null,'Kie≥pino GÛrne (WÍsierska) (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'KiliÒskiego');
INSERT INTO busstop (Id,street) VALUES (null,'KiliÒskiego (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Kliniczna - Szpital');
INSERT INTO busstop (Id,street) VALUES (null,'Klonowa');
INSERT INTO busstop (Id,street) VALUES (null,'KnyszyÒska');
INSERT INTO busstop (Id,street) VALUES (null,'KnyszyÒska (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Kokoszki - Poczta');
INSERT INTO busstop (Id,street) VALUES (null,'Kolonia Mysia');
INSERT INTO busstop (Id,street) VALUES (null,'Kolonia Mysia ');
INSERT INTO busstop (Id,street) VALUES (null,'Kolonia Uroda');
INSERT INTO busstop (Id,street) VALUES (null,'Kolorowa');
INSERT INTO busstop (Id,street) VALUES (null,'Kolorowa (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Kolumba');
INSERT INTO busstop (Id,street) VALUES (null,'Kolumba (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Ko≥obrzeska');
INSERT INTO busstop (Id,street) VALUES (null,'Ko≥obrzeska (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Komary (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Kontenerowa (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Kopalniana');
INSERT INTO busstop (Id,street) VALUES (null,'Kopalniana (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Kopeckiego');
INSERT INTO busstop (Id,street) VALUES (null,'Korczaka (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'KosmonautÛw (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Koúciuszki');
INSERT INTO busstop (Id,street) VALUES (null,'Koúciuszki (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Kowale - Apollina');
INSERT INTO busstop (Id,street) VALUES (null,'Kowale - KasztelaÒska');
INSERT INTO busstop (Id,street) VALUES (null,'Kowale - Os. Olimp');
INSERT INTO busstop (Id,street) VALUES (null,'Kowale - Pl. Afrodyty');
INSERT INTO busstop (Id,street) VALUES (null,'Kowale - Starowiejska');
INSERT INTO busstop (Id,street) VALUES (null,'Kowale Szlachecka (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Krasickiego');
INSERT INTO busstop (Id,street) VALUES (null,'Krasickiego (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'KrÍta');
INSERT INTO busstop (Id,street) VALUES (null,'Krynicka');
INSERT INTO busstop (Id,street) VALUES (null,'Krynicka (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Krzemowa');
INSERT INTO busstop (Id,street) VALUES (null,'Krzemowa (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Ku Ujúciu (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Kujawska');
INSERT INTO busstop (Id,street) VALUES (null,'KurpiÒskiego');
INSERT INTO busstop (Id,street) VALUES (null,'KurpiÒskiego (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Kwiatowa');
INSERT INTO busstop (Id,street) VALUES (null,'Kwiatowa (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Latarnia Morska');
INSERT INTO busstop (Id,street) VALUES (null,'Lawendowe WzgÛrze');
INSERT INTO busstop (Id,street) VALUES (null,'Lawendowe WzgÛrze (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Lazurowa');
INSERT INTO busstop (Id,street) VALUES (null,'Lazurowa (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'LegionÛw');
INSERT INTO busstop (Id,street) VALUES (null,'LegionÛw (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Lenartowicza');
INSERT INTO busstop (Id,street) VALUES (null,'Lessowa');
INSERT INTO busstop (Id,street) VALUES (null,'Leszczynowa (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'LeszczyÒskich');
INSERT INTO busstop (Id,street) VALUES (null,'LeszczyÒskich (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Leúna G. - Przychodnia');
INSERT INTO busstop (Id,street) VALUES (null,'Leúna GÛra');
INSERT INTO busstop (Id,street) VALUES (null,'Liliowa');
INSERT INTO busstop (Id,street) VALUES (null,'Liliowa (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Lipce - Niegowska');
INSERT INTO busstop (Id,street) VALUES (null,'Lipce - Niegowska (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Lipowa');
INSERT INTO busstop (Id,street) VALUES (null,'Lipowa (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Lubowidzka (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Lwowska');
INSERT INTO busstop (Id,street) VALUES (null,'£agiewniki');
INSERT INTO busstop (Id,street) VALUES (null,'£anowa I (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'£anowa II (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'£anowa III (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'£anowa IV (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'£apiÒska');
INSERT INTO busstop (Id,street) VALUES (null,'£apiÒska (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'£Íczycka');
INSERT INTO busstop (Id,street) VALUES (null,'£Íczycka (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'£ostowice åwiÍtokrzyska');
INSERT INTO busstop (Id,street) VALUES (null,'£owicka');
INSERT INTO busstop (Id,street) VALUES (null,'£owicka (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'£Ûdzka (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'MaÊkowy Mleczarnia');
INSERT INTO busstop (Id,street) VALUES (null,'Maki');
INSERT INTO busstop (Id,street) VALUES (null,'Maki (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Ma≥kowo');
INSERT INTO busstop (Id,street) VALUES (null,'Ma≥omiejska (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Marsa');
INSERT INTO busstop (Id,street) VALUES (null,'Marynarska (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Matarnia PKM');
INSERT INTO busstop (Id,street) VALUES (null,'Matarnia PKM (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Matejki');
INSERT INTO busstop (Id,street) VALUES (null,'Matemblewo');
INSERT INTO busstop (Id,street) VALUES (null,'Mazurska');
INSERT INTO busstop (Id,street) VALUES (null,'Meczet');
INSERT INTO busstop (Id,street) VALUES (null,'Meteorytowa (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Mia≥ki Szlak');
INSERT INTO busstop (Id,street) VALUES (null,'Mia≥ki Szlak (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Micha≥ki Wiadukt (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Mickiewicza');
INSERT INTO busstop (Id,street) VALUES (null,'Mickiewicza (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Miedza (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Migowo');
INSERT INTO busstop (Id,street) VALUES (null,'Migowo (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Miszewo');
INSERT INTO busstop (Id,street) VALUES (null,'Miszewskiego');
INSERT INTO busstop (Id,street) VALUES (null,'Mjr Hubala');
INSERT INTO busstop (Id,street) VALUES (null,'Modra I (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Modra II (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Modra III (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Modra IV (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Mostek');
INSERT INTO busstop (Id,street) VALUES (null,'Mostek ');
INSERT INTO busstop (Id,street) VALUES (null,'Mostek (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Mostostal');
INSERT INTO busstop (Id,street) VALUES (null,'Myúliborska');
INSERT INTO busstop (Id,street) VALUES (null,'Myúliwska');
INSERT INTO busstop (Id,street) VALUES (null,'Myúliwska (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Na SzaÒcach');
INSERT INTO busstop (Id,street) VALUES (null,'Na SzaÒcach (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Na WzgÛrzu');
INSERT INTO busstop (Id,street) VALUES (null,'Na WzgÛrzu (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Na ZaspÍ');
INSERT INTO busstop (Id,street) VALUES (null,'Nabrzeøe Przemys≥owe');
INSERT INTO busstop (Id,street) VALUES (null,'Nabrzeøe Zboøowe');
INSERT INTO busstop (Id,street) VALUES (null,'Nad Jarem - Zakosy');
INSERT INTO busstop (Id,street) VALUES (null,'NadwiúlaÒska (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Nadwodna');
INSERT INTO busstop (Id,street) VALUES (null,'Naftowa');
INSERT INTO busstop (Id,street) VALUES (null,'Narodowe Centrum Øeglarstwa');
INSERT INTO busstop (Id,street) VALUES (null,'Niedzia≥kowskiego');
INSERT INTO busstop (Id,street) VALUES (null,'Niedzia≥kowskiego (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Niedüwiednik');
INSERT INTO busstop (Id,street) VALUES (null,'Niepo≥omicka');
INSERT INTO busstop (Id,street) VALUES (null,'Niepo≥omicka (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Niwki');
INSERT INTO busstop (Id,street) VALUES (null,'Niwki (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Norblina');
INSERT INTO busstop (Id,street) VALUES (null,'Nowa');
INSERT INTO busstop (Id,street) VALUES (null,'Nowa (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'NowatorÛw');
INSERT INTO busstop (Id,street) VALUES (null,'NowatorÛw (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Nowe Ogrody');
INSERT INTO busstop (Id,street) VALUES (null,'Nowiny');
INSERT INTO busstop (Id,street) VALUES (null,'Nowiny (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Nowolipie (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Nowotna');
INSERT INTO busstop (Id,street) VALUES (null,'Nowotna (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Nowy Port (GÛreckiego)');
INSERT INTO busstop (Id,street) VALUES (null,'Nowy Port (Oliwska)');
INSERT INTO busstop (Id,street) VALUES (null,'Nowy Port Szaniec Zachodni');
INSERT INTO busstop (Id,street) VALUES (null,'Nowy Port Szaniec Zachodni (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Nowy åwiat');
INSERT INTO busstop (Id,street) VALUES (null,'Nowy åwiat (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'ObroÒcÛw Westerplatte');
INSERT INTO busstop (Id,street) VALUES (null,'ObroÒcÛw Westerplatte (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'ObroÒcÛw Wybrzeøa');
INSERT INTO busstop (Id,street) VALUES (null,'ObroÒcÛw Wybrzeøa  (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Oczyszczalnia (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'OdrzaÒska');
INSERT INTO busstop (Id,street) VALUES (null,'OdrzaÒska (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Odyseusza');
INSERT INTO busstop (Id,street) VALUES (null,'Ogrodowa (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Okopowa');
INSERT INTO busstop (Id,street) VALUES (null,'Olimpijska');
INSERT INTO busstop (Id,street) VALUES (null,'Oliwa');
INSERT INTO busstop (Id,street) VALUES (null,'Oliwa PÍtla Tramwajowa');
INSERT INTO busstop (Id,street) VALUES (null,'Oliwa PÍtla Tramwajowa (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Oliwa PKP');
INSERT INTO busstop (Id,street) VALUES (null,'Oliwa PKP (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Oliwa ZOO');
INSERT INTO busstop (Id,street) VALUES (null,'OlsztyÒska');
INSERT INTO busstop (Id,street) VALUES (null,'OlsztyÒska (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Olszynka - Szko≥a');
INSERT INTO busstop (Id,street) VALUES (null,'OlszyÒska');
INSERT INTO busstop (Id,street) VALUES (null,'Opacka');
INSERT INTO busstop (Id,street) VALUES (null,'Opacka (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Opera Ba≥tycka');
INSERT INTO busstop (Id,street) VALUES (null,'Opera Ba≥tycka (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Opolska');
INSERT INTO busstop (Id,street) VALUES (null,'Opolska (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'OrnitologÛw (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Orunia GÛrna');
INSERT INTO busstop (Id,street) VALUES (null,'Orunia GÛrna (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Os. Barniewice');
INSERT INTO busstop (Id,street) VALUES (null,'Os. åwiÍtokrzyskie (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Os. Wejhera');
INSERT INTO busstop (Id,street) VALUES (null,'Osiedle Jary');
INSERT INTO busstop (Id,street) VALUES (null,'Osiedle Jary (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Osiedle åwiÍtokrzyskie');
INSERT INTO busstop (Id,street) VALUES (null,'Osiedle åwiÍtokrzyskie (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Osiedle Wejhera');
INSERT INTO busstop (Id,street) VALUES (null,'Osiedle Z≥ota Karczma');
INSERT INTO busstop (Id,street) VALUES (null,'Osowa - Obwodnica');
INSERT INTO busstop (Id,street) VALUES (null,'Osowa - Obwodnica (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Osowa PKP');
INSERT INTO busstop (Id,street) VALUES (null,'Osowa PKP (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Osowa Przesypownia');
INSERT INTO busstop (Id,street) VALUES (null,'Otomin - Dziewicza (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Otomin - PÍtla');
INSERT INTO busstop (Id,street) VALUES (null,'Otomin - Sarnia');
INSERT INTO busstop (Id,street) VALUES (null,'Otomin Dziewicza (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Otomin Sarnia');
INSERT INTO busstop (Id,street) VALUES (null,'OtomiÒska');
INSERT INTO busstop (Id,street) VALUES (null,'OtomiÒska (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Otwarta');
INSERT INTO busstop (Id,street) VALUES (null,'Otwarta (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Owczarnia');
INSERT INTO busstop (Id,street) VALUES (null,'P D P S');
INSERT INTO busstop (Id,street) VALUES (null,'PagÛrkowa');
INSERT INTO busstop (Id,street) VALUES (null,'PagÛrkowa (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Park Naukowo - Technologiczny');
INSERT INTO busstop (Id,street) VALUES (null,'Paska');
INSERT INTO busstop (Id,street) VALUES (null,'Pastelowa');
INSERT INTO busstop (Id,street) VALUES (null,'PCK');
INSERT INTO busstop (Id,street) VALUES (null,'PCK (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'PÍpowo - Skrzyøowanie (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'PGE ARENA GdaÒsk');
INSERT INTO busstop (Id,street) VALUES (null,'PGE ARENA GdaÒsk (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Piastowska');
INSERT INTO busstop (Id,street) VALUES (null,'Piastowska (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Piecewska');
INSERT INTO busstop (Id,street) VALUES (null,'Piecewska (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Piecki WileÒska');
INSERT INTO busstop (Id,street) VALUES (null,'Piecki WileÒska (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Piekarnicza');
INSERT INTO busstop (Id,street) VALUES (null,'Piekarnicza (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'PilotÛw');
INSERT INTO busstop (Id,street) VALUES (null,'Pl. Solidarnoúci');
INSERT INTO busstop (Id,street) VALUES (null,'Pl. Wolnoúci');
INSERT INTO busstop (Id,street) VALUES (null,'Pl. Wolnoúci (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Plac Komorowskiego');
INSERT INTO busstop (Id,street) VALUES (null,'Plac Solidarnoúci');
INSERT INTO busstop (Id,street) VALUES (null,'Plac Wolnoúci');
INSERT INTO busstop (Id,street) VALUES (null,'Plac Wolnoúci (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Platynowa');
INSERT INTO busstop (Id,street) VALUES (null,'Platynowa (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'P≥ocka');
INSERT INTO busstop (Id,street) VALUES (null,'P≥ocka (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'P≥oÒska - Skrzyø. (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'P≥owce');
INSERT INTO busstop (Id,street) VALUES (null,'P≥owce (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'POD - Lotnisko I (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'POD - Lotnisko II (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'POD - Lotnisko III (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Podkarpacka');
INSERT INTO busstop (Id,street) VALUES (null,'Podkarpacka (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Pohulanka (Armii Krajowej)');
INSERT INTO busstop (Id,street) VALUES (null,'Pohulanka (Armii Krajowej) (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Pok≥adowa (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Pole Namiotowe (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Politechnika');
INSERT INTO busstop (Id,street) VALUES (null,'Politechnika SKM');
INSERT INTO busstop (Id,street) VALUES (null,'Pomorska');
INSERT INTO busstop (Id,street) VALUES (null,'Pomorska - Kapliczna');
INSERT INTO busstop (Id,street) VALUES (null,'Pomorska - Kapliczna (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Pomorska - Osiedle');
INSERT INTO busstop (Id,street) VALUES (null,'Pomorska - Osiedle (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Pomorska (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Pomorskie Szko≥y Rzemios≥');
INSERT INTO busstop (Id,street) VALUES (null,'PorÍbskiego');
INSERT INTO busstop (Id,street) VALUES (null,'PorÍbskiego (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Port Lotniczy');
INSERT INTO busstop (Id,street) VALUES (null,'Potokowa');
INSERT INTO busstop (Id,street) VALUES (null,'Potokowa - Matemblewska (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Potokowa (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'PowstaÒcÛw Warszawskich');
INSERT INTO busstop (Id,street) VALUES (null,'PoznaÒska (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'PÛlnicy');
INSERT INTO busstop (Id,street) VALUES (null,'PÛlnicy (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Pruszcz Gd. - BatalionÛw Ch≥opskich');
INSERT INTO busstop (Id,street) VALUES (null,'Pruszcz Gd. - CER');
INSERT INTO busstop (Id,street) VALUES (null,'Pruszcz Gd. - Chopina');
INSERT INTO busstop (Id,street) VALUES (null,'Pruszcz Gd. - Dπbrowskiego');
INSERT INTO busstop (Id,street) VALUES (null,'Pruszcz Gd. - Drzyma≥y');
INSERT INTO busstop (Id,street) VALUES (null,'Pruszcz Gd. - Fabryczny (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Pruszcz Gd. - Komarowo');
INSERT INTO busstop (Id,street) VALUES (null,'Pruszcz Gd. - Matejki');
INSERT INTO busstop (Id,street) VALUES (null,'Pruszcz Gd. - Niemcewicza');
INSERT INTO busstop (Id,street) VALUES (null,'Pruszcz Gd. - Nowowiejskiego');
INSERT INTO busstop (Id,street) VALUES (null,'Pruszcz Gd. - PowstaÒcÛw Warszawy (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Pruszcz Gd. - Przemys≥owa (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Pruszcz Gd. - Raciborskiego');
INSERT INTO busstop (Id,street) VALUES (null,'Pruszcz Gd. - Radunica (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Pruszcz Gd. - Rondo Kaszubskie');
INSERT INTO busstop (Id,street) VALUES (null,'Pruszcz Gd. - Sienkiewicza');
INSERT INTO busstop (Id,street) VALUES (null,'Pruszcz Gd. - Urzπd Skarbowy');
INSERT INTO busstop (Id,street) VALUES (null,'Pruszcz Gd. - Walπga');
INSERT INTO busstop (Id,street) VALUES (null,'Pruszcz Gd. - Wojska Polskiego');
INSERT INTO busstop (Id,street) VALUES (null,'Pruszcz Gd. - Øwirki i Wigury');
INSERT INTO busstop (Id,street) VALUES (null,'Pruszcz GdaÒski Broniewskiego');
INSERT INTO busstop (Id,street) VALUES (null,'Pruszcz GdaÒski Chopina');
INSERT INTO busstop (Id,street) VALUES (null,'Pruszcz GdaÒski Chopina (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Pruszcz GdaÒski Dπbrowskiego');
INSERT INTO busstop (Id,street) VALUES (null,'Pruszcz GdaÒski Drzyma≥y');
INSERT INTO busstop (Id,street) VALUES (null,'Pruszcz GdaÒski Emilii Plater');
INSERT INTO busstop (Id,street) VALUES (null,'Pruszcz GdaÒski Komarowo');
INSERT INTO busstop (Id,street) VALUES (null,'Pruszcz GdaÒski Matejki');
INSERT INTO busstop (Id,street) VALUES (null,'Pruszcz GdaÒski Niemcewicza');
INSERT INTO busstop (Id,street) VALUES (null,'Pruszcz GdaÒski Niemcewicza (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Pruszcz GdaÒski ObroÒcÛw Westerplatte');
INSERT INTO busstop (Id,street) VALUES (null,'Pruszcz GdaÒski ObroÒcÛw Westerplatte (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Pruszcz GdaÒski Osiedle Kasprowicza');
INSERT INTO busstop (Id,street) VALUES (null,'Pruszcz GdaÒski Osiedle Kasprowicza (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Pruszcz GdaÒski Osiedle Piastowskie');
INSERT INTO busstop (Id,street) VALUES (null,'Pruszcz GdaÒski Osiedle Piastowskie (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Pruszcz GdaÒski Osiedle WschÛd');
INSERT INTO busstop (Id,street) VALUES (null,'Pruszcz GdaÒski PowstaÒcÛw Warszawy (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Pruszcz GdaÒski Przemys≥owa (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Pruszcz GdaÒski Radunica (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Pruszcz GdaÒski Reymonta (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Pruszcz GdaÒski Sienkiewicza (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Pruszcz GdaÒski Walπga');
INSERT INTO busstop (Id,street) VALUES (null,'Pruszcz GdaÒski Wiúniewskiego');
INSERT INTO busstop (Id,street) VALUES (null,'Pruszcz GdaÒski Wysockiego (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Pruszcz GdaÒski Øwirki i Wigury');
INSERT INTO busstop (Id,street) VALUES (null,'Przebiúniegowa');
INSERT INTO busstop (Id,street) VALUES (null,'Przebiúniegowa (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Przegalina');
INSERT INTO busstop (Id,street) VALUES (null,'Przegalina (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'PrzegaliÒska');
INSERT INTO busstop (Id,street) VALUES (null,'PrzegaliÒska - Schronisko (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'PrzegaliÒska (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Przejazdowo');
INSERT INTO busstop (Id,street) VALUES (null,'Przejazdowo "Makro"');
INSERT INTO busstop (Id,street) VALUES (null,'Przejazdowo (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Przejazdowo £πkowa (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Przejazdowo Sezonowa (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Przemian (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Przemyska');
INSERT INTO busstop (Id,street) VALUES (null,'Przemyska (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'PrzerÛbka');
INSERT INTO busstop (Id,street) VALUES (null,'Przybrzeøna (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Przychodnia');
INSERT INTO busstop (Id,street) VALUES (null,'Przymorze SKM');
INSERT INTO busstop (Id,street) VALUES (null,'Przymorze SKM (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Przymorze Wielkie');
INSERT INTO busstop (Id,street) VALUES (null,'Przymorze Wielkie (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'PrzyrodnikÛw');
INSERT INTO busstop (Id,street) VALUES (null,'PrzystaÒ');
INSERT INTO busstop (Id,street) VALUES (null,'PrzystaÒ (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'PrzystaÒ Øeglugi');
INSERT INTO busstop (Id,street) VALUES (null,'Przytulna');
INSERT INTO busstop (Id,street) VALUES (null,'Przytulna (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Przywidzka');
INSERT INTO busstop (Id,street) VALUES (null,'Przywidzka (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Ptasia');
INSERT INTO busstop (Id,street) VALUES (null,'Ptasia (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Radarowa');
INSERT INTO busstop (Id,street) VALUES (null,'Radiowa (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Rafineria');
INSERT INTO busstop (Id,street) VALUES (null,'Rafineria - brama 8');
INSERT INTO busstop (Id,street) VALUES (null,'Rafineria (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Rakietowa (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Reformacka');
INSERT INTO busstop (Id,street) VALUES (null,'Reformacka (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Reja');
INSERT INTO busstop (Id,street) VALUES (null,'Rejtana');
INSERT INTO busstop (Id,street) VALUES (null,'Rejtana (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Reymonta');
INSERT INTO busstop (Id,street) VALUES (null,'RÍbiechowo');
INSERT INTO busstop (Id,street) VALUES (null,'RÍbiechowo PKP (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'RÍbowo');
INSERT INTO busstop (Id,street) VALUES (null,'RogaliÒska');
INSERT INTO busstop (Id,street) VALUES (null,'RogaliÒska (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Roz≥ogi');
INSERT INTO busstop (Id,street) VALUES (null,'Rozstaje');
INSERT INTO busstop (Id,street) VALUES (null,'RÛwna');
INSERT INTO busstop (Id,street) VALUES (null,'Rybacka');
INSERT INTO busstop (Id,street) VALUES (null,'Rybaki GÛrne');
INSERT INTO busstop (Id,street) VALUES (null,'Rybo≥owcÛw');
INSERT INTO busstop (Id,street) VALUES (null,'Rynarzewo (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Rzeczypospolitej');
INSERT INTO busstop (Id,street) VALUES (null,'Rzeczypospolitej - Ko≥obrzeska');
INSERT INTO busstop (Id,street) VALUES (null,'Rzeczypospolitej - Ko≥obrzeska (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Rzeünicka');
INSERT INTO busstop (Id,street) VALUES (null,'Rzeünicka (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Sandomierska');
INSERT INTO busstop (Id,street) VALUES (null,'Sandomierska  (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Sandomierska - OlszyÒska');
INSERT INTO busstop (Id,street) VALUES (null,'Saturna');
INSERT INTO busstop (Id,street) VALUES (null,'Sπsiedzka (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Schuberta');
INSERT INTO busstop (Id,street) VALUES (null,'Schumana');
INSERT INTO busstop (Id,street) VALUES (null,'SDO "Z≥ota JesieÒ" (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Siedlce');
INSERT INTO busstop (Id,street) VALUES (null,'Siedlce (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Siedleckiego');
INSERT INTO busstop (Id,street) VALUES (null,'Sienna Grobla');
INSERT INTO busstop (Id,street) VALUES (null,'Sierpowa');
INSERT INTO busstop (Id,street) VALUES (null,'Sierpowa (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Sikorskiego');
INSERT INTO busstop (Id,street) VALUES (null,'Sikorskiego (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'SkarøyÒskiego');
INSERT INTO busstop (Id,street) VALUES (null,'Skrajna');
INSERT INTO busstop (Id,street) VALUES (null,'S≥owackiego - Dzia≥ki (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Sobieszewko (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Sobieszewko Oúrodek (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Sobieszewo Most (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Sobieszewo Wyspa');
INSERT INTO busstop (Id,street) VALUES (null,'Sobieszewo Wyspa (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Sobieszewska (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Sobieszewska Pastwa 1 (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Sobieszewska Pastwa 2 (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'SobÛtki (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'So≥dka');
INSERT INTO busstop (Id,street) VALUES (null,'Sopocka');
INSERT INTO busstop (Id,street) VALUES (null,'Sopocka (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Sopot 23 Marca (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Sopot 3 Maja');
INSERT INTO busstop (Id,street) VALUES (null,'Sopot 3 Maja (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Sopot ArchitektÛw (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Sopot Bitwy pod P≥owcami');
INSERT INTO busstop (Id,street) VALUES (null,'Sopot BohaterÛw Monte Cassino (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Sopot Brodwino (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Sopot Brodwino Szko≥a (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Sopot Chopina');
INSERT INTO busstop (Id,street) VALUES (null,'Sopot Ergo Arena');
INSERT INTO busstop (Id,street) VALUES (null,'Sopot Goyki (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Sopot Grand Hotel');
INSERT INTO busstop (Id,street) VALUES (null,'Sopot Grunwaldzka');
INSERT INTO busstop (Id,street) VALUES (null,'Sopot Hestii');
INSERT INTO busstop (Id,street) VALUES (null,'Sopot Hotel "Marina"');
INSERT INTO busstop (Id,street) VALUES (null,'Sopot JunakÛw (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Sopot Kamienny Potok SKM');
INSERT INTO busstop (Id,street) VALUES (null,'Sopot Kasztanowa');
INSERT INTO busstop (Id,street) VALUES (null,'Sopot Kasztanowa (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Sopot Kochanowskiego');
INSERT INTO busstop (Id,street) VALUES (null,'Sopot Kolberga (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Sopot Korty Tenisowe (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Sopot £okietka (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Sopot Malczewskiego');
INSERT INTO busstop (Id,street) VALUES (null,'Sopot Malczewskiego (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Sopot Ma≥opolska (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Sopot M≥yÒska (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Sopot OkrÍøna (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Sopot Os. Przylesie');
INSERT INTO busstop (Id,street) VALUES (null,'Sopot PKP');
INSERT INTO busstop (Id,street) VALUES (null,'Sopot PKP - Niepodleg≥oúci');
INSERT INTO busstop (Id,street) VALUES (null,'Sopot PKP - Niepodleg≥oúci (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Sopot Plac KusociÒskiego (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Sopot Polna');
INSERT INTO busstop (Id,street) VALUES (null,'Sopot Polna (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Sopot Reja');
INSERT INTO busstop (Id,street) VALUES (null,'Sopot Reja (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Sopot Sanatorium "Leúnik"');
INSERT INTO busstop (Id,street) VALUES (null,'Sopot Sikorskiego');
INSERT INTO busstop (Id,street) VALUES (null,'Sopot Smolna (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Sopot Uniwersytet GdaÒski');
INSERT INTO busstop (Id,street) VALUES (null,'Sopot Uniwersytet GdaÒski (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Sopot Wejherowska');
INSERT INTO busstop (Id,street) VALUES (null,'Sopot W≥adys≥awa IV');
INSERT INTO busstop (Id,street) VALUES (null,'Sopot Wybickiego');
INSERT INTO busstop (Id,street) VALUES (null,'SÛwki');
INSERT INTO busstop (Id,street) VALUES (null,'SÛwki (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Spacerowa (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Spadochroniarzy');
INSERT INTO busstop (Id,street) VALUES (null,'Srebrna');
INSERT INTO busstop (Id,street) VALUES (null,'Srebrna (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Srebrniki');
INSERT INTO busstop (Id,street) VALUES (null,'Srebrzysko');
INSERT INTO busstop (Id,street) VALUES (null,'Srebrzysko (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Starogardzka');
INSERT INTO busstop (Id,street) VALUES (null,'Startowa');
INSERT INTO busstop (Id,street) VALUES (null,'Startowa - Hynka');
INSERT INTO busstop (Id,street) VALUES (null,'Staw WrÛbla');
INSERT INTO busstop (Id,street) VALUES (null,'Staw WrÛbla (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Steczka');
INSERT INTO busstop (Id,street) VALUES (null,'Steczka (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Sternicza');
INSERT INTO busstop (Id,street) VALUES (null,'Stocznia PÛ≥nocna');
INSERT INTO busstop (Id,street) VALUES (null,'Stocznia PÛ≥nocna (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Stocznia SKM');
INSERT INTO busstop (Id,street) VALUES (null,'StoczniowcÛw (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Stogi Pasanil');
INSERT INTO busstop (Id,street) VALUES (null,'Stogi Plaøa');
INSERT INTO busstop (Id,street) VALUES (null,'Stogi-GÛrki Zachodnie');
INSERT INTO busstop (Id,street) VALUES (null,'Stokrotki');
INSERT INTO busstop (Id,street) VALUES (null,'Stokrotki (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Strzelnica (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Strzyøa PKM');
INSERT INTO busstop (Id,street) VALUES (null,'Strzyøa PKM (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Subis≥awa');
INSERT INTO busstop (Id,street) VALUES (null,'Subis≥awa (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Suchanino');
INSERT INTO busstop (Id,street) VALUES (null,'Sucharskiego');
INSERT INTO busstop (Id,street) VALUES (null,'Sucharskiego - PKP (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Swojska');
INSERT INTO busstop (Id,street) VALUES (null,'Swojska (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'SzadÛ≥ki');
INSERT INTO busstop (Id,street) VALUES (null,'SzadÛ≥ki (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'SzadÛ≥ki Obwodnica (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Szafarnia');
INSERT INTO busstop (Id,street) VALUES (null,'Szafarnia (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'SzczÍúliwa');
INSERT INTO busstop (Id,street) VALUES (null,'SzczÍúliwa (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Szpital Marynarki Wojennej');
INSERT INTO busstop (Id,street) VALUES (null,'Szpital Zakaüny');
INSERT INTO busstop (Id,street) VALUES (null,'Sztutowska');
INSERT INTO busstop (Id,street) VALUES (null,'Szybowcowa');
INSERT INTO busstop (Id,street) VALUES (null,'Szybowcowa (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'åluza');
INSERT INTO busstop (Id,street) VALUES (null,'ånieøna');
INSERT INTO busstop (Id,street) VALUES (null,'ånieøna (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'årÛdmieúcie SKM');
INSERT INTO busstop (Id,street) VALUES (null,'åw. Wojciech');
INSERT INTO busstop (Id,street) VALUES (null,'åw. Wojciech - OstrÛøek');
INSERT INTO busstop (Id,street) VALUES (null,'åw. Wojciech - OstrÛøek (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'åw. Wojciech (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'åwibnieÒska');
INSERT INTO busstop (Id,street) VALUES (null,'åwibnieÒska - Sklep (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'åwibnieÒska (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'åwibno - Przychodnia (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'åwiÍtego Ducha');
INSERT INTO busstop (Id,street) VALUES (null,'åwiÍtokrzyska (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Tamka');
INSERT INTO busstop (Id,street) VALUES (null,'Tarasy (Bema) (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Tarcice');
INSERT INTO busstop (Id,street) VALUES (null,'Tarcice (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Targ Rybny');
INSERT INTO busstop (Id,street) VALUES (null,'Targowisko (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Teatr Miniatura / Radio GdaÒsk (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Teatr Szekspirowski (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Telewizyjna (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Terminal DCT');
INSERT INTO busstop (Id,street) VALUES (null,'Tetmajera');
INSERT INTO busstop (Id,street) VALUES (null,'TÍczowa (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Tra≥owa - Szko≥a');
INSERT INTO busstop (Id,street) VALUES (null,'Tra≥owa - Szko≥a (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'TransportowcÛw');
INSERT INTO busstop (Id,street) VALUES (null,'TransportowcÛw (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Traugutta');
INSERT INTO busstop (Id,street) VALUES (null,'Traugutta - Sobieskiego');
INSERT INTO busstop (Id,street) VALUES (null,'Trawki (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Turystyczna (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Twarda');
INSERT INTO busstop (Id,street) VALUES (null,'Twierdza Wis≥oujúcie');
INSERT INTO busstop (Id,street) VALUES (null,'Twierdza Wis≥oujúcie (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Tysiπclecia');
INSERT INTO busstop (Id,street) VALUES (null,'Tysiπclecia (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Uczniowska');
INSERT INTO busstop (Id,street) VALUES (null,'Ujeúcisko');
INSERT INTO busstop (Id,street) VALUES (null,'Ukoúna');
INSERT INTO busstop (Id,street) VALUES (null,'Ukoúna (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Unimor (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Uniwersyteckie Centrum Kliniczne');
INSERT INTO busstop (Id,street) VALUES (null,'Uniwersytet');
INSERT INTO busstop (Id,street) VALUES (null,'Uniwersytet (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Uniwersytet Medyczny');
INSERT INTO busstop (Id,street) VALUES (null,'Uniwersytet Medyczny (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Uphagena');
INSERT INTO busstop (Id,street) VALUES (null,'Uranowa');
INSERT INTO busstop (Id,street) VALUES (null,'Uranowa (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Urzπd Dozoru Technicznego');
INSERT INTO busstop (Id,street) VALUES (null,'Urzπd Dozoru Technicznego (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Urzπd Miejski');
INSERT INTO busstop (Id,street) VALUES (null,'Urzπd Miejski (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Urzπd WojewÛdzki / Marsza≥kowski');
INSERT INTO busstop (Id,street) VALUES (null,'Uzdrowiskowa');
INSERT INTO busstop (Id,street) VALUES (null,'Uzdrowiskowa (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Wagnera');
INSERT INTO busstop (Id,street) VALUES (null,'Wagnera (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Wa≥owa');
INSERT INTO busstop (Id,street) VALUES (null,'Wa≥y Piastowskie');
INSERT INTO busstop (Id,street) VALUES (null,'Wa≥y Piastowskie  (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Wa≥y Piastowskie (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'WarneÒska');
INSERT INTO busstop (Id,street) VALUES (null,'WarneÒska (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Wczasy');
INSERT INTO busstop (Id,street) VALUES (null,'Westerplatte');
INSERT INTO busstop (Id,street) VALUES (null,'WÍgorzowa');
INSERT INTO busstop (Id,street) VALUES (null,'WÍgorzowa (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'WÍze≥ Harfa (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'WÍze≥ Karczemki');
INSERT INTO busstop (Id,street) VALUES (null,'WÍze≥ Karczemki (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'WÍze≥ Kliniczna');
INSERT INTO busstop (Id,street) VALUES (null,'WÍze≥ Lipce (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Wieniec (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Wieniecka (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Wieøycka');
INSERT INTO busstop (Id,street) VALUES (null,'Wieøycka (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Wilanowska');
INSERT INTO busstop (Id,street) VALUES (null,'Wilanowska (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Wiolinowa');
INSERT INTO busstop (Id,street) VALUES (null,'Wiosny LudÛw');
INSERT INTO busstop (Id,street) VALUES (null,'Wiúlinka Brzegowa (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Wiúlinka Piaskowa (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Wiúlinka Pocztowa');
INSERT INTO busstop (Id,street) VALUES (null,'Wiúlinka Sportowa (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Wiúlinka Szkolna');
INSERT INTO busstop (Id,street) VALUES (null,'Wiúlinka Szkolna (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'W≥adys≥awa IV');
INSERT INTO busstop (Id,street) VALUES (null,'W≥adys≥awa IV (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Wojska Polskiego');
INSERT INTO busstop (Id,street) VALUES (null,'Wojska Polskiego (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Wo≥kowyska');
INSERT INTO busstop (Id,street) VALUES (null,'Wo≥kowyska (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Wronki');
INSERT INTO busstop (Id,street) VALUES (null,'Wronki (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'WrÛbla');
INSERT INTO busstop (Id,street) VALUES (null,'WrÛbla (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Wrzeszcz PKP');
INSERT INTO busstop (Id,street) VALUES (null,'Wysoka Galaktyczna');
INSERT INTO busstop (Id,street) VALUES (null,'WyspiaÒskiego');
INSERT INTO busstop (Id,street) VALUES (null,'WyspiaÒskiego (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Wyzwolenia');
INSERT INTO busstop (Id,street) VALUES (null,'Wyzwolenia - Mar. Polskiej');
INSERT INTO busstop (Id,street) VALUES (null,'Wyzwolenia - Mar. Polskiej (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Wyzwolenia - Marynarki Polskiej');
INSERT INTO busstop (Id,street) VALUES (null,'Wyzwolenia - Marynarki Polskiej (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Wyzwolenia (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Zabytkowa');
INSERT INTO busstop (Id,street) VALUES (null,'Zabytkowa (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Zacna');
INSERT INTO busstop (Id,street) VALUES (null,'Zacna (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Zagony (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Zagroble (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Zajezdnia');
INSERT INTO busstop (Id,street) VALUES (null,'Zajezdnia (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Zajezdnia NOWY PORT');
INSERT INTO busstop (Id,street) VALUES (null,'Zajezdnia Nowy Port (dla wysiad.)');
INSERT INTO busstop (Id,street) VALUES (null,'Zajezdnia NOWY PORT (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Zak≥ad Utylizacyjny');
INSERT INTO busstop (Id,street) VALUES (null,'Zakoniczyn');
INSERT INTO busstop (Id,street) VALUES (null,'Zakoniczyn (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'ZakopiaÒska');
INSERT INTO busstop (Id,street) VALUES (null,'ZakopiaÒska (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Zamenhofa');
INSERT INTO busstop (Id,street) VALUES (null,'Zamenhofa (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Zaroúlak');
INSERT INTO busstop (Id,street) VALUES (null,'Zaroúlak  (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Zaroúlak (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Zaspa');
INSERT INTO busstop (Id,street) VALUES (null,'Zaspa - Szpital');
INSERT INTO busstop (Id,street) VALUES (null,'Zaspa - Szpital (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Zaspa SKM');
INSERT INTO busstop (Id,street) VALUES (null,'Zawodzie');
INSERT INTO busstop (Id,street) VALUES (null,'Zawodzie (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Zbieøna');
INSERT INTO busstop (Id,street) VALUES (null,'Zbieøna (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'ZespÛ≥ SzkÛ≥ Morskich');
INSERT INTO busstop (Id,street) VALUES (null,'ZespÛ≥ SzkÛ≥ Morskich (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Zielony Most');
INSERT INTO busstop (Id,street) VALUES (null,'Zielony Stok');
INSERT INTO busstop (Id,street) VALUES (null,'Zielony Stok (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Zimna');
INSERT INTO busstop (Id,street) VALUES (null,'Zimna (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Z≥ota Karczma');
INSERT INTO busstop (Id,street) VALUES (null,'Z≥ota Karczma (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Zremb (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Zwierzyniecka');
INSERT INTO busstop (Id,street) VALUES (null,'Zwierzyniecka (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'èrÛdlana (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Øabi Kruk');
INSERT INTO busstop (Id,street) VALUES (null,'Øabi Kruk  (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Øabianka SKM');
INSERT INTO busstop (Id,street) VALUES (null,'Øaglowa - AmberExpo');
INSERT INTO busstop (Id,street) VALUES (null,'Øaglowa - AmberExpo (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Øukowo Dworcowa');
INSERT INTO busstop (Id,street) VALUES (null,'Øukowo Fenikowskiego');
INSERT INTO busstop (Id,street) VALUES (null,'Øukowo S≥oneczna (n/ø)');
INSERT INTO busstop (Id,street) VALUES (null,'Øukowo Urzπd Gminy');
INSERT INTO busstop (Id,street) VALUES (null,'Øuraw');
INSERT INTO busstop (Id,street) VALUES (null,'Øwirki i Wigury');
INSERT INTO busstop (Id,street) VALUES (null,'Øyczliwa (n/ø)');
