ALTER DATABASE `Planer` DEFAULT CHARACTER SET utf8 COLLATE utf8_polish_ci;

ALTER TABLE `events` CONVERT TO CHARACTER SET utf8 COLLATE utf8_polish_ci;

ALTER TABLE `events` DEFAULT CHARACTER SET utf8 COLLATE utf8_polish_ci;

ALTER TABLE `busstop` CONVERT TO CHARACTER SET utf8 COLLATE utf8_polish_ci;

ALTER TABLE `busstop` DEFAULT CHARACTER SET utf8 COLLATE utf8_polish_ci;